FROM public.ecr.aws/lambda/python:3.13

# Copy model files (already in assignment)
COPY hair_classifier_empty.onnx.data .
COPY hair_classifier_empty.onnx .

# Copy your lambda function code
COPY lambda_function.py .

# Install dependencies
RUN pip install pillow onnxruntime

# Set the Lambda handler
CMD ["lambda_function.lambda_handler"]
